import { render, screen } from "@testing-library/react";
import "@testing-library/jest-dom";
import React from "react";
import ErrorBoundary from "./ErrorBoundary";

const ComponentWithError = () => {
  throw new Error();
};

global.alert = jest.fn();

describe("<ErrorBoundary> window", () => {
  it("displays error message on error generated by child", () => {
    render(
      <ErrorBoundary>
        <ComponentWithError />
      </ErrorBoundary>
    );
    expect(screen.getByTestId("error-message")).toBeVisible();
  });
});
